"""Multiple Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OIT5b6c5N06cf6oeDDXNkzAbKY7UW49_
"""
# Importing Libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

# Reading Data-File
mydf = pd.read_csv("data.csv")

# Defining Dependent and Independent Variables
X = mydf.iloc[:, 2:32].values  # Independent Variable
Y = mydf.iloc[:, 1]  # Dependent Variable

# Splitting in training and testing data
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.1, random_state=1)

# Training the data
model = LogisticRegression()
model.fit(X_train, Y_train)
print("Model Created Successfully")

# Predicting Values
Y_pred_test = model.predict(X_test)
Y_pred_train = model.predict(X_train)

# Showing Accuracy
print("Accuracy for Testing data=",
      metrics.accuracy_score(Y_test, Y_pred_test)*100, '%')
print("Accuracy for Training data=", metrics.accuracy_score(
    Y_train, Y_pred_train)*100, '%')

# Predicting for custom Input
X_new = (7.76, 24.54, 47.92, 181, 0.05263, 0.04362, 0, 0, 0.1587, 0.05884, 0.3857, 1.428, 2.548, 19.15, 0.007189,
         0.00466, 0, 0, 0.02676, 0.002783, 9.456, 30.37, 59.16, 268.6, 0.08996, 0.06444, 0, 0, 0.2871, 0.07039)
input_data_as_numpy_array = np.asarray(X_new)
input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)
Y_new = model.predict(input_data_reshaped)
print(Y_new)

# 'B' --> Benign --> Non-Cancerous
# 'M' --> Malignant --> Cancerous
